CREATE TABLE smsdeliver (
  Command VARBINARY(200) DEFAULT NULL,
  seq1 BIGINT(10) NOT NULL DEFAULT '0',
  seq2 INTEGER(10) NOT NULL DEFAULT '0',
  seq3 INTEGER(10) NOT NULL DEFAULT '0',
  recvTime TIMESTAMP(19) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  resp CHAR(1) DEFAULT NULL,
  retries INTEGER(2) DEFAULT '0',
  PRIMARY KEY (seq1, seq2, seq3))TYPE=InnoDB;

COMMIT;

