CREATE TABLE test1 (
  seq1 INTEGER(11) NOT NULL DEFAULT '0',
  seq2 INTEGER(11) NOT NULL DEFAULT '0',
  seq3 INTEGER(11) NOT NULL DEFAULT '0',
  resp CHAR(1) DEFAULT NULL,
  PRIMARY KEY (seq2, seq1, seq3))TYPE=InnoDB;

COMMIT;

