package com.zbensoft.mmsmp.db.domain;


public class AlarmManger {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.alarm_key
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String alarmKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.name
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.alarm_level_code
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String alarmLevelCode;
	
	private String alarmLevelName;
	private String alarmOrigin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.first_time_sec
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String firstTimeSec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.frequency_time_sec
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String frequencyTimeSec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.handle_class
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String handleClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.class_paramter
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String classParamter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.delete_flag
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private Integer deleteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alarm_manger.remark
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	private String remark;
	
	private String firstTimeSecStart;

	private String firstTimeSecEnd;
	private String alarmEmailManageId;
	private String alarmEmailManageName;

	public String getAlarmEmailManageName() {
		return alarmEmailManageName;
	}

	public void setAlarmEmailManageName(String alarmEmailManageName) {
		this.alarmEmailManageName = alarmEmailManageName;
	}

	public String getAlarmEmailManageId() {
		return alarmEmailManageId;
	}

	public void setAlarmEmailManageId(String alarmEmailManageId) {
		this.alarmEmailManageId = alarmEmailManageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.alarm_key
	 * @return  the value of alarm_manger.alarm_key
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getAlarmKey() {
		return alarmKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.alarm_key
	 * @param alarmKey  the value for alarm_manger.alarm_key
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setAlarmKey(String alarmKey) {
		this.alarmKey = alarmKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.name
	 * @return  the value of alarm_manger.name
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.name
	 * @param name  the value for alarm_manger.name
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.alarm_level_code
	 * @return  the value of alarm_manger.alarm_level_code
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getAlarmLevelCode() {
		return alarmLevelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.alarm_level_code
	 * @param alarmLevelCode  the value for alarm_manger.alarm_level_code
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setAlarmLevelCode(String alarmLevelCode) {
		this.alarmLevelCode = alarmLevelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.first_time_sec
	 * @return  the value of alarm_manger.first_time_sec
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getFirstTimeSec() {
		return firstTimeSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.first_time_sec
	 * @param firstTimeSec  the value for alarm_manger.first_time_sec
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setFirstTimeSec(String firstTimeSec) {
		this.firstTimeSec = firstTimeSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.frequency_time_sec
	 * @return  the value of alarm_manger.frequency_time_sec
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getFrequencyTimeSec() {
		return frequencyTimeSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.frequency_time_sec
	 * @param frequencyTimeSec  the value for alarm_manger.frequency_time_sec
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setFrequencyTimeSec(String frequencyTimeSec) {
		this.frequencyTimeSec = frequencyTimeSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.handle_class
	 * @return  the value of alarm_manger.handle_class
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getHandleClass() {
		return handleClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.handle_class
	 * @param handleClass  the value for alarm_manger.handle_class
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setHandleClass(String handleClass) {
		this.handleClass = handleClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.class_paramter
	 * @return  the value of alarm_manger.class_paramter
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getClassParamter() {
		return classParamter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.class_paramter
	 * @param classParamter  the value for alarm_manger.class_paramter
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setClassParamter(String classParamter) {
		this.classParamter = classParamter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.delete_flag
	 * @return  the value of alarm_manger.delete_flag
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public Integer getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.delete_flag
	 * @param deleteFlag  the value for alarm_manger.delete_flag
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alarm_manger.remark
	 * @return  the value of alarm_manger.remark
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alarm_manger.remark
	 * @param remark  the value for alarm_manger.remark
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFirstTimeSecStart() {
		return firstTimeSecStart;
	}

	public void setFirstTimeSecStart(String firstTimeSecStart) {
		this.firstTimeSecStart = firstTimeSecStart;
	}

	public String getFirstTimeSecEnd() {
		return firstTimeSecEnd;
	}

	public void setFirstTimeSecEnd(String firstTimeSecEnd) {
		this.firstTimeSecEnd = firstTimeSecEnd;
	}

	public String getAlarmLevelName() {
		return alarmLevelName;
	}

	public void setAlarmLevelName(String alarmLevelName) {
		this.alarmLevelName = alarmLevelName;
	}

	public String getAlarmOrigin() {
		return alarmOrigin;
	}

	public void setAlarmOrigin(String alarmOrigin) {
		this.alarmOrigin = alarmOrigin;
	}

}