package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ApplicationServer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_server.application_server_code
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    private String applicationServerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_server.ip_addr
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_server.name
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_server.last_time
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_server.remark
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_server.application_server_code
     *
     * @return the value of application_server.application_server_code
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public String getApplicationServerCode() {
        return applicationServerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_server.application_server_code
     *
     * @param applicationServerCode the value for application_server.application_server_code
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public void setApplicationServerCode(String applicationServerCode) {
        this.applicationServerCode = applicationServerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_server.ip_addr
     *
     * @return the value of application_server.ip_addr
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_server.ip_addr
     *
     * @param ipAddr the value for application_server.ip_addr
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_server.name
     *
     * @return the value of application_server.name
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_server.name
     *
     * @param name the value for application_server.name
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_server.last_time
     *
     * @return the value of application_server.last_time
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_server.last_time
     *
     * @param lastTime the value for application_server.last_time
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_server.remark
     *
     * @return the value of application_server.remark
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_server.remark
     *
     * @param remark the value for application_server.remark
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}