package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ContentSensitiveWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.content_sensitive_word_id
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    private String contentSensitiveWordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.create_time
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.update_time
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.word
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.remark
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.creater_user
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    private String createrUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_sensitive_word.type
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    private Integer type;
    
    
    
    
    private String updateTimeStart;
	private String updateTimeEnd;
	private String createTimeStart;
	private String createTimeEnd;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.content_sensitive_word_id
     *
     * @return the value of content_sensitive_word.content_sensitive_word_id
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public String getContentSensitiveWordId() {
        return contentSensitiveWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.content_sensitive_word_id
     *
     * @param contentSensitiveWordId the value for content_sensitive_word.content_sensitive_word_id
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setContentSensitiveWordId(String contentSensitiveWordId) {
        this.contentSensitiveWordId = contentSensitiveWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.create_time
     *
     * @return the value of content_sensitive_word.create_time
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.create_time
     *
     * @param createTime the value for content_sensitive_word.create_time
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.update_time
     *
     * @return the value of content_sensitive_word.update_time
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.update_time
     *
     * @param updateTime the value for content_sensitive_word.update_time
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.word
     *
     * @return the value of content_sensitive_word.word
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.word
     *
     * @param word the value for content_sensitive_word.word
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.remark
     *
     * @return the value of content_sensitive_word.remark
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.remark
     *
     * @param remark the value for content_sensitive_word.remark
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.creater_user
     *
     * @return the value of content_sensitive_word.creater_user
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public String getCreaterUser() {
        return createrUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.creater_user
     *
     * @param createrUser the value for content_sensitive_word.creater_user
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setCreaterUser(String createrUser) {
        this.createrUser = createrUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_sensitive_word.type
     *
     * @return the value of content_sensitive_word.type
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_sensitive_word.type
     *
     * @param type the value for content_sensitive_word.type
     *
     * @mbg.generated Fri Aug 24 15:18:19 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

	public String getUpdateTimeStart() {
		return updateTimeStart;
	}

	public void setUpdateTimeStart(String updateTimeStart) {
		this.updateTimeStart = updateTimeStart;
	}

	public String getUpdateTimeEnd() {
		return updateTimeEnd;
	}

	public void setUpdateTimeEnd(String updateTimeEnd) {
		this.updateTimeEnd = updateTimeEnd;
	}

	public String getCreateTimeStart() {
		return createTimeStart;
	}

	public void setCreateTimeStart(String createTimeStart) {
		this.createTimeStart = createTimeStart;
	}

	public String getCreateTimeEnd() {
		return createTimeEnd;
	}

	public void setCreateTimeEnd(String createTimeEnd) {
		this.createTimeEnd = createTimeEnd;
	}

}