package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ContentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.content_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String contentInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.product_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String productInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.cp_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String cpInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.content_code
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String contentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.content_name
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String contentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.content_remark
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String contentRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.create_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.author
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.status
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.content_path
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String contentPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.content_type
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private Integer contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.key_word
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String keyWord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.is_realtime
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private Integer isRealtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.realtime_content_url
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String realtimeContentUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.reject_reason
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String rejectReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.is_apply_delete
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private Integer isApplyDelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.web_pic
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String webPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.start_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.end_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.singer
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String singer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.feature_str
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String featureStr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.aduit_user
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String aduitUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.version_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String versionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.is_send
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private Integer isSend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.sms_text
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String smsText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.last_audit_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private Date lastAuditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.set_send_time_user
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String setSendTimeUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_info.ad_send_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	private String adSendId;
	
	
	private Date lastAuditTimeStart;
	private Date lastAuditTimeEnd;
	private String createTimeStart;
	private String createTimeEnd;
	
	private String startTimeStart;
	private String startTimeEnd;
	private String endTimeStart;
	private String endTimeEnd;
	
	private String cpName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.content_info_id
	 * @return  the value of content_info.content_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getContentInfoId() {
		return contentInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.content_info_id
	 * @param contentInfoId  the value for content_info.content_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setContentInfoId(String contentInfoId) {
		this.contentInfoId = contentInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.product_info_id
	 * @return  the value of content_info.product_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getProductInfoId() {
		return productInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.product_info_id
	 * @param productInfoId  the value for content_info.product_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setProductInfoId(String productInfoId) {
		this.productInfoId = productInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.cp_info_id
	 * @return  the value of content_info.cp_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getCpInfoId() {
		return cpInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.cp_info_id
	 * @param cpInfoId  the value for content_info.cp_info_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setCpInfoId(String cpInfoId) {
		this.cpInfoId = cpInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.content_code
	 * @return  the value of content_info.content_code
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getContentCode() {
		return contentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.content_code
	 * @param contentCode  the value for content_info.content_code
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setContentCode(String contentCode) {
		this.contentCode = contentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.content_name
	 * @return  the value of content_info.content_name
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getContentName() {
		return contentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.content_name
	 * @param contentName  the value for content_info.content_name
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setContentName(String contentName) {
		this.contentName = contentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.content_remark
	 * @return  the value of content_info.content_remark
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getContentRemark() {
		return contentRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.content_remark
	 * @param contentRemark  the value for content_info.content_remark
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setContentRemark(String contentRemark) {
		this.contentRemark = contentRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.create_time
	 * @return  the value of content_info.create_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.create_time
	 * @param createTime  the value for content_info.create_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.author
	 * @return  the value of content_info.author
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.author
	 * @param author  the value for content_info.author
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.status
	 * @return  the value of content_info.status
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.status
	 * @param status  the value for content_info.status
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.content_path
	 * @return  the value of content_info.content_path
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getContentPath() {
		return contentPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.content_path
	 * @param contentPath  the value for content_info.content_path
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setContentPath(String contentPath) {
		this.contentPath = contentPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.content_type
	 * @return  the value of content_info.content_type
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Integer getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.content_type
	 * @param contentType  the value for content_info.content_type
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setContentType(Integer contentType) {
		this.contentType = contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.key_word
	 * @return  the value of content_info.key_word
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getKeyWord() {
		return keyWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.key_word
	 * @param keyWord  the value for content_info.key_word
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.is_realtime
	 * @return  the value of content_info.is_realtime
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Integer getIsRealtime() {
		return isRealtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.is_realtime
	 * @param isRealtime  the value for content_info.is_realtime
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setIsRealtime(Integer isRealtime) {
		this.isRealtime = isRealtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.realtime_content_url
	 * @return  the value of content_info.realtime_content_url
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getRealtimeContentUrl() {
		return realtimeContentUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.realtime_content_url
	 * @param realtimeContentUrl  the value for content_info.realtime_content_url
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setRealtimeContentUrl(String realtimeContentUrl) {
		this.realtimeContentUrl = realtimeContentUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.reject_reason
	 * @return  the value of content_info.reject_reason
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getRejectReason() {
		return rejectReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.reject_reason
	 * @param rejectReason  the value for content_info.reject_reason
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.is_apply_delete
	 * @return  the value of content_info.is_apply_delete
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Integer getIsApplyDelete() {
		return isApplyDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.is_apply_delete
	 * @param isApplyDelete  the value for content_info.is_apply_delete
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setIsApplyDelete(Integer isApplyDelete) {
		this.isApplyDelete = isApplyDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.web_pic
	 * @return  the value of content_info.web_pic
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getWebPic() {
		return webPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.web_pic
	 * @param webPic  the value for content_info.web_pic
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setWebPic(String webPic) {
		this.webPic = webPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.start_time
	 * @return  the value of content_info.start_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.start_time
	 * @param startTime  the value for content_info.start_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.end_time
	 * @return  the value of content_info.end_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.end_time
	 * @param endTime  the value for content_info.end_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.singer
	 * @return  the value of content_info.singer
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getSinger() {
		return singer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.singer
	 * @param singer  the value for content_info.singer
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setSinger(String singer) {
		this.singer = singer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.feature_str
	 * @return  the value of content_info.feature_str
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getFeatureStr() {
		return featureStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.feature_str
	 * @param featureStr  the value for content_info.feature_str
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setFeatureStr(String featureStr) {
		this.featureStr = featureStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.aduit_user
	 * @return  the value of content_info.aduit_user
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getAduitUser() {
		return aduitUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.aduit_user
	 * @param aduitUser  the value for content_info.aduit_user
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setAduitUser(String aduitUser) {
		this.aduitUser = aduitUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.version_id
	 * @return  the value of content_info.version_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.version_id
	 * @param versionId  the value for content_info.version_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setVersionId(String versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.is_send
	 * @return  the value of content_info.is_send
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Integer getIsSend() {
		return isSend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.is_send
	 * @param isSend  the value for content_info.is_send
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setIsSend(Integer isSend) {
		this.isSend = isSend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.sms_text
	 * @return  the value of content_info.sms_text
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getSmsText() {
		return smsText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.sms_text
	 * @param smsText  the value for content_info.sms_text
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setSmsText(String smsText) {
		this.smsText = smsText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.last_audit_time
	 * @return  the value of content_info.last_audit_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public Date getLastAuditTime() {
		return lastAuditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.last_audit_time
	 * @param lastAuditTime  the value for content_info.last_audit_time
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setLastAuditTime(Date lastAuditTime) {
		this.lastAuditTime = lastAuditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.set_send_time_user
	 * @return  the value of content_info.set_send_time_user
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getSetSendTimeUser() {
		return setSendTimeUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.set_send_time_user
	 * @param setSendTimeUser  the value for content_info.set_send_time_user
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setSetSendTimeUser(String setSendTimeUser) {
		this.setSendTimeUser = setSendTimeUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_info.ad_send_id
	 * @return  the value of content_info.ad_send_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public String getAdSendId() {
		return adSendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_info.ad_send_id
	 * @param adSendId  the value for content_info.ad_send_id
	 * @mbg.generated  Fri Aug 24 15:18:19 CST 2018
	 */
	public void setAdSendId(String adSendId) {
		this.adSendId = adSendId;
	}

	public Date getLastAuditTimeStart() {
		return lastAuditTimeStart;
	}

	public void setLastAuditTimeStart(Date lastAuditTimeStart) {
		this.lastAuditTimeStart = lastAuditTimeStart;
	}

	public Date getLastAuditTimeEnd() {
		return lastAuditTimeEnd;
	}

	public void setLastAuditTimeEnd(Date lastAuditTimeEnd) {
		this.lastAuditTimeEnd = lastAuditTimeEnd;
	}

	public String getStartTimeStart() {
		return startTimeStart;
	}

	public void setStartTimeStart(String startTimeStart) {
		this.startTimeStart = startTimeStart;
	}

	public String getStartTimeEnd() {
		return startTimeEnd;
	}

	public void setStartTimeEnd(String startTimeEnd) {
		this.startTimeEnd = startTimeEnd;
	}

	public String getEndTimeStart() {
		return endTimeStart;
	}

	public void setEndTimeStart(String endTimeStart) {
		this.endTimeStart = endTimeStart;
	}

	public String getEndTimeEnd() {
		return endTimeEnd;
	}

	public void setEndTimeEnd(String endTimeEnd) {
		this.endTimeEnd = endTimeEnd;
	}

	public String getCpName() {
		return cpName;
	}

	public void setCpName(String cpName) {
		this.cpName = cpName;
	}

	public void setCreateTimeStart(String createTimeStart) {
		this.createTimeStart = createTimeStart;
	}

	public void setCreateTimeEnd(String createTimeEnd) {
		this.createTimeEnd = createTimeEnd;
	}
}