package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class CpInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_info_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.sp_info_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String spInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_name
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_addr
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.legal_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.bank_name
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.web_addr
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String webAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.bank_account
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.fax_no
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String faxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.business_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String businessPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.business_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String businessTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.business_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String businessMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.business_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String businessEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.customer_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String customerPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.customer_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String customerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.customer_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String customerMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.customer_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String customerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.login_user
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String loginUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.status
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.is_enable
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.register_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String registerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_code
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.reject_reason
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String rejectReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.tec_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String tecPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.tec_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String tecTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.tec_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String tecMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.tec_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String tecEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.finance_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String financePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.finance_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String financeTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.finance_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String financeMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.finance_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String financeEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.audit_time
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_logo
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_remark
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.register_time
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_type
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private Integer cpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.proportion
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private Double proportion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.aear
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String aear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.type
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_access_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpAccessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_access_id_extend
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpAccessIdExtend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.cp_access_url
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    private String cpAccessUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_info_id
     *
     * @return the value of cp_info.cp_info_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    
    //非数据库字段
    private String auditTimeStart;
    private String auditTimeEnd;
    private String spName;
    
    public String getCpInfoId() {
        return cpInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_info_id
     *
     * @param cpInfoId the value for cp_info.cp_info_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpInfoId(String cpInfoId) {
        this.cpInfoId = cpInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.sp_info_id
     *
     * @return the value of cp_info.sp_info_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getSpInfoId() {
        return spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.sp_info_id
     *
     * @param spInfoId the value for cp_info.sp_info_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setSpInfoId(String spInfoId) {
        this.spInfoId = spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_name
     *
     * @return the value of cp_info.cp_name
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpName() {
        return cpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_name
     *
     * @param cpName the value for cp_info.cp_name
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpName(String cpName) {
        this.cpName = cpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_addr
     *
     * @return the value of cp_info.cp_addr
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpAddr() {
        return cpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_addr
     *
     * @param cpAddr the value for cp_info.cp_addr
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpAddr(String cpAddr) {
        this.cpAddr = cpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.legal_person
     *
     * @return the value of cp_info.legal_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.legal_person
     *
     * @param legalPerson the value for cp_info.legal_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.bank_name
     *
     * @return the value of cp_info.bank_name
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.bank_name
     *
     * @param bankName the value for cp_info.bank_name
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.web_addr
     *
     * @return the value of cp_info.web_addr
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getWebAddr() {
        return webAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.web_addr
     *
     * @param webAddr the value for cp_info.web_addr
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setWebAddr(String webAddr) {
        this.webAddr = webAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.bank_account
     *
     * @return the value of cp_info.bank_account
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.bank_account
     *
     * @param bankAccount the value for cp_info.bank_account
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.fax_no
     *
     * @return the value of cp_info.fax_no
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getFaxNo() {
        return faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.fax_no
     *
     * @param faxNo the value for cp_info.fax_no
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.business_person
     *
     * @return the value of cp_info.business_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getBusinessPerson() {
        return businessPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.business_person
     *
     * @param businessPerson the value for cp_info.business_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setBusinessPerson(String businessPerson) {
        this.businessPerson = businessPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.business_tel
     *
     * @return the value of cp_info.business_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getBusinessTel() {
        return businessTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.business_tel
     *
     * @param businessTel the value for cp_info.business_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setBusinessTel(String businessTel) {
        this.businessTel = businessTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.business_mobile
     *
     * @return the value of cp_info.business_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getBusinessMobile() {
        return businessMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.business_mobile
     *
     * @param businessMobile the value for cp_info.business_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setBusinessMobile(String businessMobile) {
        this.businessMobile = businessMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.business_email
     *
     * @return the value of cp_info.business_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getBusinessEmail() {
        return businessEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.business_email
     *
     * @param businessEmail the value for cp_info.business_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setBusinessEmail(String businessEmail) {
        this.businessEmail = businessEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.customer_person
     *
     * @return the value of cp_info.customer_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCustomerPerson() {
        return customerPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.customer_person
     *
     * @param customerPerson the value for cp_info.customer_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCustomerPerson(String customerPerson) {
        this.customerPerson = customerPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.customer_tel
     *
     * @return the value of cp_info.customer_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.customer_tel
     *
     * @param customerTel the value for cp_info.customer_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.customer_mobile
     *
     * @return the value of cp_info.customer_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.customer_mobile
     *
     * @param customerMobile the value for cp_info.customer_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.customer_email
     *
     * @return the value of cp_info.customer_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.customer_email
     *
     * @param customerEmail the value for cp_info.customer_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.login_user
     *
     * @return the value of cp_info.login_user
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getLoginUser() {
        return loginUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.login_user
     *
     * @param loginUser the value for cp_info.login_user
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.status
     *
     * @return the value of cp_info.status
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.status
     *
     * @param status the value for cp_info.status
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.is_enable
     *
     * @return the value of cp_info.is_enable
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.is_enable
     *
     * @param isEnable the value for cp_info.is_enable
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.register_email
     *
     * @return the value of cp_info.register_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getRegisterEmail() {
        return registerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.register_email
     *
     * @param registerEmail the value for cp_info.register_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setRegisterEmail(String registerEmail) {
        this.registerEmail = registerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_code
     *
     * @return the value of cp_info.cp_code
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpCode() {
        return cpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_code
     *
     * @param cpCode the value for cp_info.cp_code
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpCode(String cpCode) {
        this.cpCode = cpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.reject_reason
     *
     * @return the value of cp_info.reject_reason
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.reject_reason
     *
     * @param rejectReason the value for cp_info.reject_reason
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.tec_person
     *
     * @return the value of cp_info.tec_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getTecPerson() {
        return tecPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.tec_person
     *
     * @param tecPerson the value for cp_info.tec_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setTecPerson(String tecPerson) {
        this.tecPerson = tecPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.tec_tel
     *
     * @return the value of cp_info.tec_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getTecTel() {
        return tecTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.tec_tel
     *
     * @param tecTel the value for cp_info.tec_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setTecTel(String tecTel) {
        this.tecTel = tecTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.tec_mobile
     *
     * @return the value of cp_info.tec_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getTecMobile() {
        return tecMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.tec_mobile
     *
     * @param tecMobile the value for cp_info.tec_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setTecMobile(String tecMobile) {
        this.tecMobile = tecMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.tec_email
     *
     * @return the value of cp_info.tec_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getTecEmail() {
        return tecEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.tec_email
     *
     * @param tecEmail the value for cp_info.tec_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setTecEmail(String tecEmail) {
        this.tecEmail = tecEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.finance_person
     *
     * @return the value of cp_info.finance_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getFinancePerson() {
        return financePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.finance_person
     *
     * @param financePerson the value for cp_info.finance_person
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setFinancePerson(String financePerson) {
        this.financePerson = financePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.finance_tel
     *
     * @return the value of cp_info.finance_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getFinanceTel() {
        return financeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.finance_tel
     *
     * @param financeTel the value for cp_info.finance_tel
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setFinanceTel(String financeTel) {
        this.financeTel = financeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.finance_mobile
     *
     * @return the value of cp_info.finance_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getFinanceMobile() {
        return financeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.finance_mobile
     *
     * @param financeMobile the value for cp_info.finance_mobile
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setFinanceMobile(String financeMobile) {
        this.financeMobile = financeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.finance_email
     *
     * @return the value of cp_info.finance_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getFinanceEmail() {
        return financeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.finance_email
     *
     * @param financeEmail the value for cp_info.finance_email
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setFinanceEmail(String financeEmail) {
        this.financeEmail = financeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.audit_time
     *
     * @return the value of cp_info.audit_time
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.audit_time
     *
     * @param auditTime the value for cp_info.audit_time
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_logo
     *
     * @return the value of cp_info.cp_logo
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpLogo() {
        return cpLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_logo
     *
     * @param cpLogo the value for cp_info.cp_logo
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpLogo(String cpLogo) {
        this.cpLogo = cpLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_remark
     *
     * @return the value of cp_info.cp_remark
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpRemark() {
        return cpRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_remark
     *
     * @param cpRemark the value for cp_info.cp_remark
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpRemark(String cpRemark) {
        this.cpRemark = cpRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.register_time
     *
     * @return the value of cp_info.register_time
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.register_time
     *
     * @param registerTime the value for cp_info.register_time
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_type
     *
     * @return the value of cp_info.cp_type
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Integer getCpType() {
        return cpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_type
     *
     * @param cpType the value for cp_info.cp_type
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpType(Integer cpType) {
        this.cpType = cpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.proportion
     *
     * @return the value of cp_info.proportion
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Double getProportion() {
        return proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.proportion
     *
     * @param proportion the value for cp_info.proportion
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setProportion(Double proportion) {
        this.proportion = proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.aear
     *
     * @return the value of cp_info.aear
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getAear() {
        return aear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.aear
     *
     * @param aear the value for cp_info.aear
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setAear(String aear) {
        this.aear = aear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.type
     *
     * @return the value of cp_info.type
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.type
     *
     * @param type the value for cp_info.type
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_access_id
     *
     * @return the value of cp_info.cp_access_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpAccessId() {
        return cpAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_access_id
     *
     * @param cpAccessId the value for cp_info.cp_access_id
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpAccessId(String cpAccessId) {
        this.cpAccessId = cpAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_access_id_extend
     *
     * @return the value of cp_info.cp_access_id_extend
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpAccessIdExtend() {
        return cpAccessIdExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_access_id_extend
     *
     * @param cpAccessIdExtend the value for cp_info.cp_access_id_extend
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpAccessIdExtend(String cpAccessIdExtend) {
        this.cpAccessIdExtend = cpAccessIdExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.cp_access_url
     *
     * @return the value of cp_info.cp_access_url
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public String getCpAccessUrl() {
        return cpAccessUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cp_info.cp_access_url
     *
     * @param cpAccessUrl the value for cp_info.cp_access_url
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    public void setCpAccessUrl(String cpAccessUrl) {
        this.cpAccessUrl = cpAccessUrl;
    }

	public String getAuditTimeStart() {
		return auditTimeStart;
	}

	public void setAuditTimeStart(String auditTimeStart) {
		this.auditTimeStart = auditTimeStart;
	}

	public String getAuditTimeEnd() {
		return auditTimeEnd;
	}

	public void setAuditTimeEnd(String auditTimeEnd) {
		this.auditTimeEnd = auditTimeEnd;
	}

	public String getSpName() {
		return spName;
	}

	public void setSpName(String spName) {
		this.spName = spName;
	}
}