package com.zbensoft.mmsmp.db.domain;

public class MobileSegment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_segment.mobile_segment_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    private String mobileSegmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_segment.segment
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    private String segment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_segment.province_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_segment.city_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_segment.area_code
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_segment.mobile_segment_id
     *
     * @return the value of mobile_segment.mobile_segment_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public String getMobileSegmentId() {
        return mobileSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_segment.mobile_segment_id
     *
     * @param mobileSegmentId the value for mobile_segment.mobile_segment_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public void setMobileSegmentId(String mobileSegmentId) {
        this.mobileSegmentId = mobileSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_segment.segment
     *
     * @return the value of mobile_segment.segment
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public String getSegment() {
        return segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_segment.segment
     *
     * @param segment the value for mobile_segment.segment
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public void setSegment(String segment) {
        this.segment = segment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_segment.province_id
     *
     * @return the value of mobile_segment.province_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_segment.province_id
     *
     * @param provinceId the value for mobile_segment.province_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_segment.city_id
     *
     * @return the value of mobile_segment.city_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_segment.city_id
     *
     * @param cityId the value for mobile_segment.city_id
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_segment.area_code
     *
     * @return the value of mobile_segment.area_code
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_segment.area_code
     *
     * @param areaCode the value for mobile_segment.area_code
     *
     * @mbg.generated Tue Aug 28 10:12:24 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }
}