package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_info_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String productInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.company_code
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.company_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.cp_access_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String cpAccessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.cp_access_id_extend
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String cpAccessIdExtend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_order_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String productOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.order_type
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.run_status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer runStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.order_fee
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Double orderFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.on_demand_fee
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Double onDemandFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.on_demand_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String onDemandRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.fee_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String feeRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.send_content_mode
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer sendContentMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.send_mode
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer sendMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.is_default
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.key_world
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String keyWorld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.classification
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.order_command
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String orderCommand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.web_pic_url
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String webPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.wap_pic_url
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String wapPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.on_demand_command
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String onDemandCommand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_source
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer productSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_on_demand_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String productOnDemandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.bookman_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String bookmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_type
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.cooperation_proportion
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String cooperationProportion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.compose_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String composeTimeinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.audit_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String auditTimeinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.proof_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String proofTimeinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.pro_audit_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String proAuditTimeinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.audit_user
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String auditUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.audit_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String auditRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String productRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.operation_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private String operationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.is_package
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer isPackage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.priority
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.deal_status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer dealStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.apply_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.queue_num
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Long queueNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.is_present
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    private Integer isPresent;

    private ProductService productService;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_info_id
     *
     * @return the value of product_info.product_info_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProductInfoId() {
        return productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_info_id
     *
     * @param productInfoId the value for product_info.product_info_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductInfoId(String productInfoId) {
        this.productInfoId = productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.company_code
     *
     * @return the value of product_info.company_code
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.company_code
     *
     * @param companyCode the value for product_info.company_code
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.company_name
     *
     * @return the value of product_info.company_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.company_name
     *
     * @param companyName the value for product_info.company_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.cp_access_id
     *
     * @return the value of product_info.cp_access_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getCpAccessId() {
        return cpAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.cp_access_id
     *
     * @param cpAccessId the value for product_info.cp_access_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setCpAccessId(String cpAccessId) {
        this.cpAccessId = cpAccessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.cp_access_id_extend
     *
     * @return the value of product_info.cp_access_id_extend
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getCpAccessIdExtend() {
        return cpAccessIdExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.cp_access_id_extend
     *
     * @param cpAccessIdExtend the value for product_info.cp_access_id_extend
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setCpAccessIdExtend(String cpAccessIdExtend) {
        this.cpAccessIdExtend = cpAccessIdExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_order_id
     *
     * @return the value of product_info.product_order_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProductOrderId() {
        return productOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_order_id
     *
     * @param productOrderId the value for product_info.product_order_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductOrderId(String productOrderId) {
        this.productOrderId = productOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.order_type
     *
     * @return the value of product_info.order_type
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.order_type
     *
     * @param orderType the value for product_info.order_type
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.status
     *
     * @return the value of product_info.status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.status
     *
     * @param status the value for product_info.status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.run_status
     *
     * @return the value of product_info.run_status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.run_status
     *
     * @param runStatus the value for product_info.run_status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setRunStatus(Integer runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_time
     *
     * @return the value of product_info.update_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_time
     *
     * @param updateTime the value for product_info.update_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.remark
     *
     * @return the value of product_info.remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.remark
     *
     * @param remark the value for product_info.remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.order_fee
     *
     * @return the value of product_info.order_fee
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Double getOrderFee() {
        return orderFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.order_fee
     *
     * @param orderFee the value for product_info.order_fee
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOrderFee(Double orderFee) {
        this.orderFee = orderFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.on_demand_fee
     *
     * @return the value of product_info.on_demand_fee
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Double getOnDemandFee() {
        return onDemandFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.on_demand_fee
     *
     * @param onDemandFee the value for product_info.on_demand_fee
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOnDemandFee(Double onDemandFee) {
        this.onDemandFee = onDemandFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.on_demand_remark
     *
     * @return the value of product_info.on_demand_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getOnDemandRemark() {
        return onDemandRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.on_demand_remark
     *
     * @param onDemandRemark the value for product_info.on_demand_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOnDemandRemark(String onDemandRemark) {
        this.onDemandRemark = onDemandRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.fee_remark
     *
     * @return the value of product_info.fee_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getFeeRemark() {
        return feeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.fee_remark
     *
     * @param feeRemark the value for product_info.fee_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setFeeRemark(String feeRemark) {
        this.feeRemark = feeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.send_content_mode
     *
     * @return the value of product_info.send_content_mode
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getSendContentMode() {
        return sendContentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.send_content_mode
     *
     * @param sendContentMode the value for product_info.send_content_mode
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setSendContentMode(Integer sendContentMode) {
        this.sendContentMode = sendContentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.send_mode
     *
     * @return the value of product_info.send_mode
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getSendMode() {
        return sendMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.send_mode
     *
     * @param sendMode the value for product_info.send_mode
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setSendMode(Integer sendMode) {
        this.sendMode = sendMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.is_default
     *
     * @return the value of product_info.is_default
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.is_default
     *
     * @param isDefault the value for product_info.is_default
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.key_world
     *
     * @return the value of product_info.key_world
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getKeyWorld() {
        return keyWorld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.key_world
     *
     * @param keyWorld the value for product_info.key_world
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setKeyWorld(String keyWorld) {
        this.keyWorld = keyWorld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.classification
     *
     * @return the value of product_info.classification
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.classification
     *
     * @param classification the value for product_info.classification
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setClassification(String classification) {
        this.classification = classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.order_command
     *
     * @return the value of product_info.order_command
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getOrderCommand() {
        return orderCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.order_command
     *
     * @param orderCommand the value for product_info.order_command
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOrderCommand(String orderCommand) {
        this.orderCommand = orderCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.web_pic_url
     *
     * @return the value of product_info.web_pic_url
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getWebPicUrl() {
        return webPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.web_pic_url
     *
     * @param webPicUrl the value for product_info.web_pic_url
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setWebPicUrl(String webPicUrl) {
        this.webPicUrl = webPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.wap_pic_url
     *
     * @return the value of product_info.wap_pic_url
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getWapPicUrl() {
        return wapPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.wap_pic_url
     *
     * @param wapPicUrl the value for product_info.wap_pic_url
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setWapPicUrl(String wapPicUrl) {
        this.wapPicUrl = wapPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.on_demand_command
     *
     * @return the value of product_info.on_demand_command
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getOnDemandCommand() {
        return onDemandCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.on_demand_command
     *
     * @param onDemandCommand the value for product_info.on_demand_command
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOnDemandCommand(String onDemandCommand) {
        this.onDemandCommand = onDemandCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_source
     *
     * @return the value of product_info.product_source
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getProductSource() {
        return productSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_source
     *
     * @param productSource the value for product_info.product_source
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductSource(Integer productSource) {
        this.productSource = productSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_on_demand_id
     *
     * @return the value of product_info.product_on_demand_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProductOnDemandId() {
        return productOnDemandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_on_demand_id
     *
     * @param productOnDemandId the value for product_info.product_on_demand_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductOnDemandId(String productOnDemandId) {
        this.productOnDemandId = productOnDemandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.bookman_name
     *
     * @return the value of product_info.bookman_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getBookmanName() {
        return bookmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.bookman_name
     *
     * @param bookmanName the value for product_info.bookman_name
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setBookmanName(String bookmanName) {
        this.bookmanName = bookmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_type
     *
     * @return the value of product_info.product_type
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_type
     *
     * @param productType the value for product_info.product_type
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.cooperation_proportion
     *
     * @return the value of product_info.cooperation_proportion
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getCooperationProportion() {
        return cooperationProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.cooperation_proportion
     *
     * @param cooperationProportion the value for product_info.cooperation_proportion
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setCooperationProportion(String cooperationProportion) {
        this.cooperationProportion = cooperationProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.compose_timeinterval
     *
     * @return the value of product_info.compose_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getComposeTimeinterval() {
        return composeTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.compose_timeinterval
     *
     * @param composeTimeinterval the value for product_info.compose_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setComposeTimeinterval(String composeTimeinterval) {
        this.composeTimeinterval = composeTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.audit_timeinterval
     *
     * @return the value of product_info.audit_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getAuditTimeinterval() {
        return auditTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.audit_timeinterval
     *
     * @param auditTimeinterval the value for product_info.audit_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setAuditTimeinterval(String auditTimeinterval) {
        this.auditTimeinterval = auditTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.proof_timeinterval
     *
     * @return the value of product_info.proof_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProofTimeinterval() {
        return proofTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.proof_timeinterval
     *
     * @param proofTimeinterval the value for product_info.proof_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProofTimeinterval(String proofTimeinterval) {
        this.proofTimeinterval = proofTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.pro_audit_timeinterval
     *
     * @return the value of product_info.pro_audit_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProAuditTimeinterval() {
        return proAuditTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.pro_audit_timeinterval
     *
     * @param proAuditTimeinterval the value for product_info.pro_audit_timeinterval
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProAuditTimeinterval(String proAuditTimeinterval) {
        this.proAuditTimeinterval = proAuditTimeinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.audit_user
     *
     * @return the value of product_info.audit_user
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.audit_user
     *
     * @param auditUser the value for product_info.audit_user
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.audit_remark
     *
     * @return the value of product_info.audit_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.audit_remark
     *
     * @param auditRemark the value for product_info.audit_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_remark
     *
     * @return the value of product_info.product_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getProductRemark() {
        return productRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_remark
     *
     * @param productRemark the value for product_info.product_remark
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setProductRemark(String productRemark) {
        this.productRemark = productRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.operation_id
     *
     * @return the value of product_info.operation_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public String getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.operation_id
     *
     * @param operationId the value for product_info.operation_id
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.is_package
     *
     * @return the value of product_info.is_package
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getIsPackage() {
        return isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.is_package
     *
     * @param isPackage the value for product_info.is_package
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setIsPackage(Integer isPackage) {
        this.isPackage = isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.priority
     *
     * @return the value of product_info.priority
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.priority
     *
     * @param priority the value for product_info.priority
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.deal_status
     *
     * @return the value of product_info.deal_status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.deal_status
     *
     * @param dealStatus the value for product_info.deal_status
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.apply_time
     *
     * @return the value of product_info.apply_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.apply_time
     *
     * @param applyTime the value for product_info.apply_time
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.queue_num
     *
     * @return the value of product_info.queue_num
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Long getQueueNum() {
        return queueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.queue_num
     *
     * @param queueNum the value for product_info.queue_num
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setQueueNum(Long queueNum) {
        this.queueNum = queueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.is_present
     *
     * @return the value of product_info.is_present
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public Integer getIsPresent() {
        return isPresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.is_present
     *
     * @param isPresent the value for product_info.is_present
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    public void setIsPresent(Integer isPresent) {
        this.isPresent = isPresent;
    }

	public ProductService getProductService() {
		return productService;
	}

	public void setProductService(ProductService productService) {
		this.productService = productService;
	}

}