package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ProductServiceExtend {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.product_service_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String productServiceId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.product_info_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String productInfoId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.is_confirm
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer isConfirm;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.is_present
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer isPresent;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.confirm_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String confirmPrompt;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.succ_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String succPrompt;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.canncel_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String canncelPrompt;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.popularize_start_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
   private Date popularizeStartTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.popularize_end_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
   private Date popularizeEndTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.is_free
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer isFree;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.free_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   
   private Integer freeTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.billing_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String billingId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.discount_remark
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String discountRemark;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.discount_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String discountId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.need_confirm
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer needConfirm;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.send_num
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer sendNum;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.order_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer orderCommandMatch;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.order_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String orderAccess;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.order_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer orderAccessMatch;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.cancel_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer cancelCommandMatch;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.cancel_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String cancelAccess;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.cancel_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer cancelAccessMatch;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.on_demand_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer onDemandCommandMatch;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.on_demand_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String onDemandAccess;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.on_demand_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer onDemandAccessMatch;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.eff_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
   private Date effTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.exp_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
   private Date expTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.is_alone_order
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer isAloneOrder;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.notify_type
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer notifyType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.product_city
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String productCity;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.product_service_period_grade
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String productServicePeriodGrade;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.product_service_grade
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String productServiceGrade;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.product_credit
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String productCredit;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.status
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private Integer status;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product_service.report_message_url
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   private String reportMessageUrl;
   
   private String spProductId;
   
   private String spInfoId;
   
   private String companyCode;
   
   private String productInfoName;
   
   private Integer newBuyTimes;
   
   private double newBuySum;
   

private Integer orderTimes;
   
   private Integer newOrderTimes;
   
   private  Double onDemandFee;
   
   private  Double buyFee;
   
   private Integer newBuyer;

private String YearMonth;
   
   private Double TotalMonth;
   
   private Double sum;
   
   private Double orderSum;
   
   private Double buySum;
   
   private Integer orderCount;
   private String province;
   
   private Integer buyCount;
   
   private Integer unsubscribe;
   
   private Double newTotal;
   private Double newOrderSum;
   public Integer getUnsubscribe() {
	return unsubscribe;
}

public void setUnsubscribe(Integer unsubscribe) {
	this.unsubscribe = unsubscribe;
}

public double getNewBuySum() {
	   return newBuySum;
   }
   
   public void setNewBuySum(double newBuySum) {
	   this.newBuySum = newBuySum;
   }
   
   public Integer getNewBuyTimes() {
	   return newBuyTimes;
   }
   
   public void setNewBuyTimes(Integer newBuyTimes) {
	   this.newBuyTimes = newBuyTimes;
   }
   
   public Integer getNewOrderTimes() {
	   return newOrderTimes;
   }
   
   public void setNewOrderTimes(Integer newOrderTimes) {
	   this.newOrderTimes = newOrderTimes;
   }
   public Double getBuyFee() {
	   return buyFee;
   }
   
   public void setBuyFee(Double buyFee) {
	   this.buyFee = buyFee;
   }
   
   public Integer getNewBuyer() {
	   return newBuyer;
   }
   
   public void setNewBuyer(Integer newBuyer) {
	   this.newBuyer = newBuyer;
   }
   
   public String getProvince() {
	   return province;
   }
   
   public void setProvince(String province) {
	   this.province = province;
   }

   public String getSpInfoId() {
	return spInfoId;
}

public Double getSum() {
	return sum;
}

public void setSum(Double sum) {
	this.sum = sum;
}

public Double getOrderSum() {
	return orderSum;
}

public void setOrderSum(Double orderSum) {
	this.orderSum = orderSum;
}

public Double getBuySum() {
	return buySum;
}

public void setBuySum(Double buySum) {
	this.buySum = buySum;
}

public Integer getOrderCount() {
	return orderCount;
}

public void setOrderCount(Integer orderCount) {
	this.orderCount = orderCount;
}

public Integer getBuyCount() {
	return buyCount;
}

public void setBuyCount(Integer buyCount) {
	this.buyCount = buyCount;
}

public void setTotalMonth(Double totalMonth) {
	TotalMonth = totalMonth;
}

public void setSpInfoId(String spInfoId) {
	this.spInfoId = spInfoId;
}

public String getCompanyCode() {
	return companyCode;
}

public void setCompanyCode(String companyCode) {
	this.companyCode = companyCode;
}

public Integer getOrderTimes() {
	return orderTimes;
}

public void setOrderTimes(Integer orderTimes) {
	this.orderTimes = orderTimes;
}

public Double getOnDemandFee() {
	return onDemandFee;
}

public void setOnDemandFee(Double onDemandFee) {
	this.onDemandFee = onDemandFee;
}

public String getYearMonth() {
	return YearMonth;
}

public void setYearMonth(String yearMonth) {
	YearMonth = yearMonth;
}

public Double getTotalMonth() {
	return TotalMonth;
}

public void setTotalMonth() {
	if(this.getOnDemandFee()!=null&&this.getOrderTimes()!=null)
	{TotalMonth = this.getOnDemandFee()*this.getOrderTimes();
	}
	}

public Double getRatioByNextYear() {
	return ratioByNextYear;
}

public void setRatioByNextYear(Double ratioByNextYear) {
	this.ratioByNextYear = ratioByNextYear;
}

public Double getRatioByNearMonth() {
	return ratioByNearMonth;
}

public void setRatioByNearMonth(Double ratioByNearMonth) {
	this.ratioByNearMonth = ratioByNearMonth;
}

private Double ratioByNextYear;
   
   private Double ratioByNearMonth; 
   
   public String getSpProductId() {
	return spProductId;
}

public void setSpProductId(String spProductId) {
	this.spProductId = spProductId;
}

public String getProductInfoName() {
	return productInfoName;
}

public void setProductInfoName(String productInfoName) {
	this.productInfoName = productInfoName;
}

/**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.product_service_id
    *
    * @return the value of product_service.product_service_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   
   public String getProductServiceId() {
       return productServiceId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.product_service_id
    *
    * @param productServiceId the value for product_service.product_service_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setProductServiceId(String productServiceId) {
       this.productServiceId = productServiceId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.product_info_id
    *
    * @return the value of product_service.product_info_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getProductInfoId() {
       return productInfoId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.product_info_id
    *
    * @param productInfoId the value for product_service.product_info_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setProductInfoId(String productInfoId) {
       this.productInfoId = productInfoId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.is_confirm
    *
    * @return the value of product_service.is_confirm
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getIsConfirm() {
       return isConfirm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.is_confirm
    *
    * @param isConfirm the value for product_service.is_confirm
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setIsConfirm(Integer isConfirm) {
       this.isConfirm = isConfirm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.is_present
    *
    * @return the value of product_service.is_present
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getIsPresent() {
       return isPresent;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.is_present
    *
    * @param isPresent the value for product_service.is_present
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setIsPresent(Integer isPresent) {
       this.isPresent = isPresent;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.confirm_prompt
    *
    * @return the value of product_service.confirm_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getConfirmPrompt() {
       return confirmPrompt;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.confirm_prompt
    *
    * @param confirmPrompt the value for product_service.confirm_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setConfirmPrompt(String confirmPrompt) {
       this.confirmPrompt = confirmPrompt;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.succ_prompt
    *
    * @return the value of product_service.succ_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getSuccPrompt() {
       return succPrompt;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.succ_prompt
    *
    * @param succPrompt the value for product_service.succ_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setSuccPrompt(String succPrompt) {
       this.succPrompt = succPrompt;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.canncel_prompt
    *
    * @return the value of product_service.canncel_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getCanncelPrompt() {
       return canncelPrompt;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.canncel_prompt
    *
    * @param canncelPrompt the value for product_service.canncel_prompt
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setCanncelPrompt(String canncelPrompt) {
       this.canncelPrompt = canncelPrompt;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.popularize_start_time
    *
    * @return the value of product_service.popularize_start_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Date getPopularizeStartTime() {
       return popularizeStartTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.popularize_start_time
    *
    * @param popularizeStartTime the value for product_service.popularize_start_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setPopularizeStartTime(Date popularizeStartTime) {
       this.popularizeStartTime = popularizeStartTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.popularize_end_time
    *
    * @return the value of product_service.popularize_end_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Date getPopularizeEndTime() {
       return popularizeEndTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.popularize_end_time
    *
    * @param popularizeEndTime the value for product_service.popularize_end_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setPopularizeEndTime(Date popularizeEndTime) {
       this.popularizeEndTime = popularizeEndTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.is_free
    *
    * @return the value of product_service.is_free
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getIsFree() {
       return isFree;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.is_free
    *
    * @param isFree the value for product_service.is_free
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setIsFree(Integer isFree) {
       this.isFree = isFree;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.free_time
    *
    * @return the value of product_service.free_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getFreeTime() {
       return freeTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.free_time
    *
    * @param freeTime the value for product_service.free_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setFreeTime(Integer freeTime) {
       this.freeTime = freeTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.billing_id
    *
    * @return the value of product_service.billing_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getBillingId() {
       return billingId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.billing_id
    *
    * @param billingId the value for product_service.billing_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setBillingId(String billingId) {
       this.billingId = billingId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.discount_remark
    *
    * @return the value of product_service.discount_remark
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getDiscountRemark() {
       return discountRemark;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.discount_remark
    *
    * @param discountRemark the value for product_service.discount_remark
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setDiscountRemark(String discountRemark) {
       this.discountRemark = discountRemark;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.discount_id
    *
    * @return the value of product_service.discount_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getDiscountId() {
       return discountId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.discount_id
    *
    * @param discountId the value for product_service.discount_id
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setDiscountId(String discountId) {
       this.discountId = discountId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.need_confirm
    *
    * @return the value of product_service.need_confirm
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getNeedConfirm() {
       return needConfirm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.need_confirm
    *
    * @param needConfirm the value for product_service.need_confirm
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setNeedConfirm(Integer needConfirm) {
       this.needConfirm = needConfirm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.send_num
    *
    * @return the value of product_service.send_num
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getSendNum() {
       return sendNum;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.send_num
    *
    * @param sendNum the value for product_service.send_num
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setSendNum(Integer sendNum) {
       this.sendNum = sendNum;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.order_command_match
    *
    * @return the value of product_service.order_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getOrderCommandMatch() {
       return orderCommandMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.order_command_match
    *
    * @param orderCommandMatch the value for product_service.order_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setOrderCommandMatch(Integer orderCommandMatch) {
       this.orderCommandMatch = orderCommandMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.order_access
    *
    * @return the value of product_service.order_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getOrderAccess() {
       return orderAccess;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.order_access
    *
    * @param orderAccess the value for product_service.order_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setOrderAccess(String orderAccess) {
       this.orderAccess = orderAccess;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.order_access_match
    *
    * @return the value of product_service.order_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getOrderAccessMatch() {
       return orderAccessMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.order_access_match
    *
    * @param orderAccessMatch the value for product_service.order_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setOrderAccessMatch(Integer orderAccessMatch) {
       this.orderAccessMatch = orderAccessMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.cancel_command_match
    *
    * @return the value of product_service.cancel_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getCancelCommandMatch() {
       return cancelCommandMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.cancel_command_match
    *
    * @param cancelCommandMatch the value for product_service.cancel_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setCancelCommandMatch(Integer cancelCommandMatch) {
       this.cancelCommandMatch = cancelCommandMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.cancel_access
    *
    * @return the value of product_service.cancel_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getCancelAccess() {
       return cancelAccess;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.cancel_access
    *
    * @param cancelAccess the value for product_service.cancel_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setCancelAccess(String cancelAccess) {
       this.cancelAccess = cancelAccess;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.cancel_access_match
    *
    * @return the value of product_service.cancel_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getCancelAccessMatch() {
       return cancelAccessMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.cancel_access_match
    *
    * @param cancelAccessMatch the value for product_service.cancel_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setCancelAccessMatch(Integer cancelAccessMatch) {
       this.cancelAccessMatch = cancelAccessMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.on_demand_command_match
    *
    * @return the value of product_service.on_demand_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getOnDemandCommandMatch() {
       return onDemandCommandMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.on_demand_command_match
    *
    * @param onDemandCommandMatch the value for product_service.on_demand_command_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setOnDemandCommandMatch(Integer onDemandCommandMatch) {
       this.onDemandCommandMatch = onDemandCommandMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.on_demand_access
    *
    * @return the value of product_service.on_demand_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getOnDemandAccess() {
       return onDemandAccess;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.on_demand_access
    *
    * @param onDemandAccess the value for product_service.on_demand_access
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setOnDemandAccess(String onDemandAccess) {
       this.onDemandAccess = onDemandAccess;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.on_demand_access_match
    *
    * @return the value of product_service.on_demand_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getOnDemandAccessMatch() {
       return onDemandAccessMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.on_demand_access_match
    *
    * @param onDemandAccessMatch the value for product_service.on_demand_access_match
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setOnDemandAccessMatch(Integer onDemandAccessMatch) {
       this.onDemandAccessMatch = onDemandAccessMatch;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.eff_time
    *
    * @return the value of product_service.eff_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Date getEffTime() {
       return effTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.eff_time
    *
    * @param effTime the value for product_service.eff_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setEffTime(Date effTime) {
       this.effTime = effTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.exp_time
    *
    * @return the value of product_service.exp_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Date getExpTime() {
       return expTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.exp_time
    *
    * @param expTime the value for product_service.exp_time
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setExpTime(Date expTime) {
       this.expTime = expTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.is_alone_order
    *
    * @return the value of product_service.is_alone_order
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getIsAloneOrder() {
       return isAloneOrder;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.is_alone_order
    *
    * @param isAloneOrder the value for product_service.is_alone_order
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setIsAloneOrder(Integer isAloneOrder) {
       this.isAloneOrder = isAloneOrder;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.notify_type
    *
    * @return the value of product_service.notify_type
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getNotifyType() {
       return notifyType;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.notify_type
    *
    * @param notifyType the value for product_service.notify_type
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setNotifyType(Integer notifyType) {
       this.notifyType = notifyType;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.product_city
    *
    * @return the value of product_service.product_city
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getProductCity() {
       return productCity;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.product_city
    *
    * @param productCity the value for product_service.product_city
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setProductCity(String productCity) {
       this.productCity = productCity;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.product_service_period_grade
    *
    * @return the value of product_service.product_service_period_grade
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getProductServicePeriodGrade() {
       return productServicePeriodGrade;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.product_service_period_grade
    *
    * @param productServicePeriodGrade the value for product_service.product_service_period_grade
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setProductServicePeriodGrade(String productServicePeriodGrade) {
       this.productServicePeriodGrade = productServicePeriodGrade;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.product_service_grade
    *
    * @return the value of product_service.product_service_grade
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getProductServiceGrade() {
       return productServiceGrade;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.product_service_grade
    *
    * @param productServiceGrade the value for product_service.product_service_grade
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setProductServiceGrade(String productServiceGrade) {
       this.productServiceGrade = productServiceGrade;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.product_credit
    *
    * @return the value of product_service.product_credit
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getProductCredit() {
       return productCredit;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.product_credit
    *
    * @param productCredit the value for product_service.product_credit
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setProductCredit(String productCredit) {
       this.productCredit = productCredit;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.status
    *
    * @return the value of product_service.status
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public Integer getStatus() {
       return status;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.status
    *
    * @param status the value for product_service.status
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setStatus(Integer status) {
       this.status = status;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column product_service.report_message_url
    *
    * @return the value of product_service.report_message_url
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public String getReportMessageUrl() {
       return reportMessageUrl;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column product_service.report_message_url
    *
    * @param reportMessageUrl the value for product_service.report_message_url
    *
    * @mbg.generated Mon Sep 03 09:13:58 CST 2018
    */
   public void setReportMessageUrl(String reportMessageUrl) {
       this.reportMessageUrl = reportMessageUrl;
   }

public Double getNewTotal() {
	return newTotal;
}

public void setNewTotal(Double newTotal) {
	this.newTotal = newTotal;
}

public Double getNewOrderSum() {
	return newOrderSum;
}

public void setNewOrderSum(Double newOrderSum) {
	this.newOrderSum = newOrderSum;
}
}