package com.zbensoft.mmsmp.db.domain;

public class Proxypaymessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.GLOBALMESSAGEID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String globalmessageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.PHONENUMBER
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.CPID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String cpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.SERVICEID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String serviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.SERVICENAME
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String servicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.FEETYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String feetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.FEE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.ACCOUNTID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.STATUS
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.VALIDATECODE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String validatecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.USERTYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.SPID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String spid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.PERORID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String perorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.PRODUCTID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.CHARGEPARTY
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String chargeparty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.CREATEDATE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.UPDATEDATE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.EXTENDFILED1
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String extendfiled1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.EXTENDFIILED2
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String extendfiiled2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.PRODUCTNAME
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxypaymessage.SOURCE_TYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private String sourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.GLOBALMESSAGEID
     *
     * @return the value of proxypaymessage.GLOBALMESSAGEID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    private CooperKey cooperKey;
    public String getGlobalmessageid() {
        return globalmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.GLOBALMESSAGEID
     *
     * @param globalmessageid the value for proxypaymessage.GLOBALMESSAGEID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setGlobalmessageid(String globalmessageid) {
        this.globalmessageid = globalmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.PHONENUMBER
     *
     * @return the value of proxypaymessage.PHONENUMBER
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.PHONENUMBER
     *
     * @param phonenumber the value for proxypaymessage.PHONENUMBER
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.CPID
     *
     * @return the value of proxypaymessage.CPID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getCpid() {
        return cpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.CPID
     *
     * @param cpid the value for proxypaymessage.CPID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setCpid(String cpid) {
        this.cpid = cpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.SERVICEID
     *
     * @return the value of proxypaymessage.SERVICEID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.SERVICEID
     *
     * @param serviceid the value for proxypaymessage.SERVICEID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.SERVICENAME
     *
     * @return the value of proxypaymessage.SERVICENAME
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.SERVICENAME
     *
     * @param servicename the value for proxypaymessage.SERVICENAME
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setServicename(String servicename) {
        this.servicename = servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.FEETYPE
     *
     * @return the value of proxypaymessage.FEETYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getFeetype() {
        return feetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.FEETYPE
     *
     * @param feetype the value for proxypaymessage.FEETYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setFeetype(String feetype) {
        this.feetype = feetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.FEE
     *
     * @return the value of proxypaymessage.FEE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.FEE
     *
     * @param fee the value for proxypaymessage.FEE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setFee(String fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.ACCOUNTID
     *
     * @return the value of proxypaymessage.ACCOUNTID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.ACCOUNTID
     *
     * @param accountid the value for proxypaymessage.ACCOUNTID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.STATUS
     *
     * @return the value of proxypaymessage.STATUS
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.STATUS
     *
     * @param status the value for proxypaymessage.STATUS
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.VALIDATECODE
     *
     * @return the value of proxypaymessage.VALIDATECODE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getValidatecode() {
        return validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.VALIDATECODE
     *
     * @param validatecode the value for proxypaymessage.VALIDATECODE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setValidatecode(String validatecode) {
        this.validatecode = validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.USERTYPE
     *
     * @return the value of proxypaymessage.USERTYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.USERTYPE
     *
     * @param usertype the value for proxypaymessage.USERTYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.SPID
     *
     * @return the value of proxypaymessage.SPID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getSpid() {
        return spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.SPID
     *
     * @param spid the value for proxypaymessage.SPID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setSpid(String spid) {
        this.spid = spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.PERORID
     *
     * @return the value of proxypaymessage.PERORID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getPerorid() {
        return perorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.PERORID
     *
     * @param perorid the value for proxypaymessage.PERORID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setPerorid(String perorid) {
        this.perorid = perorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.PRODUCTID
     *
     * @return the value of proxypaymessage.PRODUCTID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.PRODUCTID
     *
     * @param productid the value for proxypaymessage.PRODUCTID
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.CHARGEPARTY
     *
     * @return the value of proxypaymessage.CHARGEPARTY
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getChargeparty() {
        return chargeparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.CHARGEPARTY
     *
     * @param chargeparty the value for proxypaymessage.CHARGEPARTY
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setChargeparty(String chargeparty) {
        this.chargeparty = chargeparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.CREATEDATE
     *
     * @return the value of proxypaymessage.CREATEDATE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.CREATEDATE
     *
     * @param createdate the value for proxypaymessage.CREATEDATE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.UPDATEDATE
     *
     * @return the value of proxypaymessage.UPDATEDATE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.UPDATEDATE
     *
     * @param updatedate the value for proxypaymessage.UPDATEDATE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.EXTENDFILED1
     *
     * @return the value of proxypaymessage.EXTENDFILED1
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getExtendfiled1() {
        return extendfiled1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.EXTENDFILED1
     *
     * @param extendfiled1 the value for proxypaymessage.EXTENDFILED1
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setExtendfiled1(String extendfiled1) {
        this.extendfiled1 = extendfiled1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.EXTENDFIILED2
     *
     * @return the value of proxypaymessage.EXTENDFIILED2
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getExtendfiiled2() {
        return extendfiiled2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.EXTENDFIILED2
     *
     * @param extendfiiled2 the value for proxypaymessage.EXTENDFIILED2
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setExtendfiiled2(String extendfiiled2) {
        this.extendfiiled2 = extendfiiled2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.PRODUCTNAME
     *
     * @return the value of proxypaymessage.PRODUCTNAME
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.PRODUCTNAME
     *
     * @param productname the value for proxypaymessage.PRODUCTNAME
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxypaymessage.SOURCE_TYPE
     *
     * @return the value of proxypaymessage.SOURCE_TYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxypaymessage.SOURCE_TYPE
     *
     * @param sourceType the value for proxypaymessage.SOURCE_TYPE
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

	public CooperKey getCooperKey() {
		return cooperKey;
	}

	public void setCooperKey(CooperKey cooperKey) {
		this.cooperKey = cooperKey;
	}
}