package com.zbensoft.mmsmp.db.domain;

public class Seqs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seqs.seqs_code
     *
     * @mbg.generated Sat Feb 24 14:05:14 CST 2018
     */
    private String seqsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seqs.seqs_curr
     *
     * @mbg.generated Sat Feb 24 14:05:14 CST 2018
     */
    private Long seqsCurr;
    
    private Long seqsNow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seqs.seqs_code
     *
     * @return the value of seqs.seqs_code
     *
     * @mbg.generated Sat Feb 24 14:05:14 CST 2018
     */
    public String getSeqsCode() {
        return seqsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seqs.seqs_code
     *
     * @param seqsCode the value for seqs.seqs_code
     *
     * @mbg.generated Sat Feb 24 14:05:14 CST 2018
     */
    public void setSeqsCode(String seqsCode) {
        this.seqsCode = seqsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seqs.seqs_curr
     *
     * @return the value of seqs.seqs_curr
     *
     * @mbg.generated Sat Feb 24 14:05:14 CST 2018
     */
    public Long getSeqsCurr() {
        return seqsCurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seqs.seqs_curr
     *
     * @param seqsCurr the value for seqs.seqs_curr
     *
     * @mbg.generated Sat Feb 24 14:05:14 CST 2018
     */
    public void setSeqsCurr(Long seqsCurr) {
        this.seqsCurr = seqsCurr;
    }

	public Long getSeqsNow() {
		return seqsNow;
	}

	public void setSeqsNow(Long seqsNow) {
		this.seqsNow = seqsNow;
	}
}