package com.zbensoft.mmsmp.db.domain;

public class StSuccRatioKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_succ_ratio.st_time
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    private String stTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_succ_ratio.province
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_succ_ratio.product_info_id
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    private String productInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_succ_ratio.sp_info_id
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    private String spInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_succ_ratio.st_time
     *
     * @return the value of st_succ_ratio.st_time
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public String getStTime() {
        return stTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_succ_ratio.st_time
     *
     * @param stTime the value for st_succ_ratio.st_time
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public void setStTime(String stTime) {
        this.stTime = stTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_succ_ratio.province
     *
     * @return the value of st_succ_ratio.province
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_succ_ratio.province
     *
     * @param province the value for st_succ_ratio.province
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_succ_ratio.product_info_id
     *
     * @return the value of st_succ_ratio.product_info_id
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public String getProductInfoId() {
        return productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_succ_ratio.product_info_id
     *
     * @param productInfoId the value for st_succ_ratio.product_info_id
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public void setProductInfoId(String productInfoId) {
        this.productInfoId = productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_succ_ratio.sp_info_id
     *
     * @return the value of st_succ_ratio.sp_info_id
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public String getSpInfoId() {
        return spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_succ_ratio.sp_info_id
     *
     * @param spInfoId the value for st_succ_ratio.sp_info_id
     *
     * @mbg.generated Mon Sep 10 10:22:28 CST 2018
     */
    public void setSpInfoId(String spInfoId) {
        this.spInfoId = spInfoId;
    }
}