package com.zbensoft.mmsmp.db.domain;

import java.util.List;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

public class SysRole extends SysRoleMenuKey{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
	@NotEmpty(message="{sysRole.roleId.notEmpty.message}")
	@Length(max=13,message="{sysRole.roleId.length}")
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.name
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
	@NotEmpty(message="{sysRole.name.notEmpty.message}")
	@Length(max=10,message="{sysRole.name.length}")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.remark
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
	@NotEmpty(message="{sysRole.remark.notEmpty.message}")
	@Length(max=23,message="{sysRole.remark.length}")
    private String remark;
	
	//展示ztree时的数据项,切勿删除
	private List<ZTreeNode> zTreeNodes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param roleId the value for sys_role.role_id
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.name
     *
     * @return the value of sys_role.name
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.name
     *
     * @param name the value for sys_role.name
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.remark
     *
     * @return the value of sys_role.remark
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.remark
     *
     * @param remark the value for sys_role.remark
     *
     * @mbg.generated Thu Jun 08 09:13:52 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public List<ZTreeNode> getzTreeNodes() {
		return zTreeNodes;
	}

	public void setzTreeNodes(List<ZTreeNode> zTreeNodes) {
		this.zTreeNodes = zTreeNodes;
	}
    
    
	  private String code;
	    public String getCode() {
	        return code;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column sys_role.code
	     *
	     * @param code the value for sys_role.code
	     *
	     * @mbg.generated Thu Jun 29 11:43:37 CST 2017
	     */
	    public void setCode(String code) {
	        this.code = code;
	    }  
    
}