package com.zbensoft.mmsmp.db.domain;

public class SystemConfigKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.application_server_code
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    private String applicationServerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.code
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.application_server_code
     *
     * @return the value of system_config.application_server_code
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    public String getApplicationServerCode() {
        return applicationServerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.application_server_code
     *
     * @param applicationServerCode the value for system_config.application_server_code
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    public void setApplicationServerCode(String applicationServerCode) {
        this.applicationServerCode = applicationServerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.code
     *
     * @return the value of system_config.code
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.code
     *
     * @param code the value for system_config.code
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    public void setCode(String code) {
        this.code = code;
    }
}