package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_id
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.user_name
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.status
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.is_first_login
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private Integer isFirstLogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_time
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.last_login_time
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.remark
	 * 
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_id
	 * 
	 * @return the value of sys_user.user_id
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	private String roleId;

	private boolean isLockedPassword = false;
	
	public boolean isLockedPassword() {
		return isLockedPassword;
	}

	public void setLockedPassword(boolean isLockedPassword) {
		this.isLockedPassword = isLockedPassword;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_id
	 * 
	 * @param userId
	 *            the value for sys_user.user_id
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.user_name
	 * 
	 * @return the value of sys_user.user_name
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.user_name
	 * 
	 * @param userName
	 *            the value for sys_user.user_name
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.status
	 * 
	 * @return the value of sys_user.status
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.status
	 * 
	 * @param status
	 *            the value for sys_user.status
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * 
	 * @return the value of sys_user.password
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * 
	 * @param password
	 *            the value for sys_user.password
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.is_first_login
	 * 
	 * @return the value of sys_user.is_first_login
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public Integer getIsFirstLogin() {
		return isFirstLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.is_first_login
	 * 
	 * @param isFirstLogin
	 *            the value for sys_user.is_first_login
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setIsFirstLogin(Integer isFirstLogin) {
		this.isFirstLogin = isFirstLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_time
	 * 
	 * @return the value of sys_user.create_time
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_time
	 * 
	 * @param createTime
	 *            the value for sys_user.create_time
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.last_login_time
	 * 
	 * @return the value of sys_user.last_login_time
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.last_login_time
	 * 
	 * @param lastLoginTime
	 *            the value for sys_user.last_login_time
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.remark
	 * 
	 * @return the value of sys_user.remark
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.remark
	 * 
	 * @param remark
	 *            the value for sys_user.remark
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}