package com.zbensoft.mmsmp.db.domain;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_type_id
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    private String taskTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.name
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.cron_expression
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.remark
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_type_id
     *
     * @return the value of task.task_type_id
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public String getTaskTypeId() {
        return taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_type_id
     *
     * @param taskTypeId the value for task.task_type_id
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public void setTaskTypeId(String taskTypeId) {
        this.taskTypeId = taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.name
     *
     * @return the value of task.name
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.name
     *
     * @param name the value for task.name
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.cron_expression
     *
     * @return the value of task.cron_expression
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.cron_expression
     *
     * @param cronExpression the value for task.cron_expression
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.remark
     *
     * @return the value of task.remark
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.remark
     *
     * @param remark the value for task.remark
     *
     * @mbg.generated Mon Jun 19 14:47:04 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}