package com.zbensoft.mmsmp.db.domain;

public class TaskType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.task_type_id
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    private String taskTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.name
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.handle_class
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    private String handleClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.status
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.remark
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.task_type_id
     *
     * @return the value of task_type.task_type_id
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public String getTaskTypeId() {
        return taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.task_type_id
     *
     * @param taskTypeId the value for task_type.task_type_id
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public void setTaskTypeId(String taskTypeId) {
        this.taskTypeId = taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.name
     *
     * @return the value of task_type.name
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.name
     *
     * @param name the value for task_type.name
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.handle_class
     *
     * @return the value of task_type.handle_class
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public String getHandleClass() {
        return handleClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.handle_class
     *
     * @param handleClass the value for task_type.handle_class
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public void setHandleClass(String handleClass) {
        this.handleClass = handleClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.status
     *
     * @return the value of task_type.status
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.status
     *
     * @param status the value for task_type.status
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.remark
     *
     * @return the value of task_type.remark
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.remark
     *
     * @param remark the value for task_type.remark
     *
     * @mbg.generated Mon Jun 19 10:20:55 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}