package com.zbensoft.mmsmp.db.domain;

public class TestTerminalProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_terminal_product.test_terminal_id
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    private String testTerminalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_terminal_product.product_info_id
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    private String productInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_terminal_product.test_terminal_id
     *
     * @return the value of test_terminal_product.test_terminal_id
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    public String getTestTerminalId() {
        return testTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_terminal_product.test_terminal_id
     *
     * @param testTerminalId the value for test_terminal_product.test_terminal_id
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    public void setTestTerminalId(String testTerminalId) {
        this.testTerminalId = testTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_terminal_product.product_info_id
     *
     * @return the value of test_terminal_product.product_info_id
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    public String getProductInfoId() {
        return productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_terminal_product.product_info_id
     *
     * @param productInfoId the value for test_terminal_product.product_info_id
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    public void setProductInfoId(String productInfoId) {
        this.productInfoId = productInfoId;
    }
}