package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String chargePhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.terminal_type
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Integer terminalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.province
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_password
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_sex
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Integer userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.profession
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_email
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_addr
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String userAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.hobby
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.postal_code
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.country
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nationality
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.marriage
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Integer marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.certificate_type
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Integer certificateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.certificate_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String certificateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.brand
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.delete_flag
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    private Integer deleteFlag;
    private String provinceCityName;
    private String parentProvinceCityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_number
     *
     * @return the value of user_info.phone_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_number
     *
     * @param phoneNumber the value for user_info.phone_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.charge_phone_number
     *
     * @return the value of user_info.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getChargePhoneNumber() {
        return chargePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.charge_phone_number
     *
     * @param chargePhoneNumber the value for user_info.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setChargePhoneNumber(String chargePhoneNumber) {
        this.chargePhoneNumber = chargePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.terminal_type
     *
     * @return the value of user_info.terminal_type
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Integer getTerminalType() {
        return terminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.terminal_type
     *
     * @param terminalType the value for user_info.terminal_type
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setTerminalType(Integer terminalType) {
        this.terminalType = terminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.province
     *
     * @return the value of user_info.province
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.province
     *
     * @param province the value for user_info.province
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city
     *
     * @return the value of user_info.city
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city
     *
     * @param city the value for user_info.city
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_password
     *
     * @return the value of user_info.user_password
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_password
     *
     * @param userPassword the value for user_info.user_password
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_sex
     *
     * @return the value of user_info.user_sex
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_sex
     *
     * @param userSex the value for user_info.user_sex
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.profession
     *
     * @return the value of user_info.profession
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.profession
     *
     * @param profession the value for user_info.profession
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_email
     *
     * @return the value of user_info.user_email
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_email
     *
     * @param userEmail the value for user_info.user_email
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_addr
     *
     * @return the value of user_info.user_addr
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getUserAddr() {
        return userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_addr
     *
     * @param userAddr the value for user_info.user_addr
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setUserAddr(String userAddr) {
        this.userAddr = userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.hobby
     *
     * @return the value of user_info.hobby
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.hobby
     *
     * @param hobby the value for user_info.hobby
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.postal_code
     *
     * @return the value of user_info.postal_code
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.postal_code
     *
     * @param postalCode the value for user_info.postal_code
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.country
     *
     * @return the value of user_info.country
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.country
     *
     * @param country the value for user_info.country
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nationality
     *
     * @return the value of user_info.nationality
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nationality
     *
     * @param nationality the value for user_info.nationality
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.marriage
     *
     * @return the value of user_info.marriage
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Integer getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.marriage
     *
     * @param marriage the value for user_info.marriage
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setMarriage(Integer marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.certificate_type
     *
     * @return the value of user_info.certificate_type
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Integer getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.certificate_type
     *
     * @param certificateType the value for user_info.certificate_type
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setCertificateType(Integer certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.certificate_number
     *
     * @return the value of user_info.certificate_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.certificate_number
     *
     * @param certificateNumber the value for user_info.certificate_number
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.brand
     *
     * @return the value of user_info.brand
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.brand
     *
     * @param brand the value for user_info.brand
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.delete_flag
     *
     * @return the value of user_info.delete_flag
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.delete_flag
     *
     * @param deleteFlag the value for user_info.delete_flag
     *
     * @mbg.generated Mon Aug 27 14:06:47 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

	public String getProvinceCityName() {
		return provinceCityName;
	}

	public void setProvinceCityName(String provinceCityName) {
		this.provinceCityName = provinceCityName;
	}

	public String getParentProvinceCityName() {
		return parentProvinceCityName;
	}

	public void setParentProvinceCityName(String parentProvinceCityName) {
		this.parentProvinceCityName = parentProvinceCityName;
	}
}