package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class UserServiceSend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.user_service_send_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String userServiceSendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.sp_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String spInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.product_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String productInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.request_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String chargePhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.content_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String contentInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.send_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.status
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.service_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer serviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.report_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.send_service_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer sendServiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.send_service_rel_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String sendServiceRelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.error_info
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String errorInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.send_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer sendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.mms_path
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String mmsPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_service_send.batch_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String batchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.user_service_send_id
     *
     * @return the value of user_service_send.user_service_send_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String reportTimeStart;
    private String reportTimeEnd;
    private String companyName;
    public String getUserServiceSendId() {
        return userServiceSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.user_service_send_id
     *
     * @param userServiceSendId the value for user_service_send.user_service_send_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setUserServiceSendId(String userServiceSendId) {
        this.userServiceSendId = userServiceSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.phone_number
     *
     * @return the value of user_service_send.phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.phone_number
     *
     * @param phoneNumber the value for user_service_send.phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.sp_info_id
     *
     * @return the value of user_service_send.sp_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getSpInfoId() {
        return spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.sp_info_id
     *
     * @param spInfoId the value for user_service_send.sp_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setSpInfoId(String spInfoId) {
        this.spInfoId = spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.product_info_id
     *
     * @return the value of user_service_send.product_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getProductInfoId() {
        return productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.product_info_id
     *
     * @param productInfoId the value for user_service_send.product_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setProductInfoId(String productInfoId) {
        this.productInfoId = productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.request_id
     *
     * @return the value of user_service_send.request_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.request_id
     *
     * @param requestId the value for user_service_send.request_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.charge_phone_number
     *
     * @return the value of user_service_send.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getChargePhoneNumber() {
        return chargePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.charge_phone_number
     *
     * @param chargePhoneNumber the value for user_service_send.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setChargePhoneNumber(String chargePhoneNumber) {
        this.chargePhoneNumber = chargePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.content_info_id
     *
     * @return the value of user_service_send.content_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getContentInfoId() {
        return contentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.content_info_id
     *
     * @param contentInfoId the value for user_service_send.content_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setContentInfoId(String contentInfoId) {
        this.contentInfoId = contentInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.send_time
     *
     * @return the value of user_service_send.send_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.send_time
     *
     * @param sendTime the value for user_service_send.send_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.status
     *
     * @return the value of user_service_send.status
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.status
     *
     * @param status the value for user_service_send.status
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.service_type
     *
     * @return the value of user_service_send.service_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.service_type
     *
     * @param serviceType the value for user_service_send.service_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.report_time
     *
     * @return the value of user_service_send.report_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.report_time
     *
     * @param reportTime the value for user_service_send.report_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.send_service_type
     *
     * @return the value of user_service_send.send_service_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getSendServiceType() {
        return sendServiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.send_service_type
     *
     * @param sendServiceType the value for user_service_send.send_service_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setSendServiceType(Integer sendServiceType) {
        this.sendServiceType = sendServiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.send_service_rel_id
     *
     * @return the value of user_service_send.send_service_rel_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getSendServiceRelId() {
        return sendServiceRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.send_service_rel_id
     *
     * @param sendServiceRelId the value for user_service_send.send_service_rel_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setSendServiceRelId(String sendServiceRelId) {
        this.sendServiceRelId = sendServiceRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.error_info
     *
     * @return the value of user_service_send.error_info
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.error_info
     *
     * @param errorInfo the value for user_service_send.error_info
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.send_type
     *
     * @return the value of user_service_send.send_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.send_type
     *
     * @param sendType the value for user_service_send.send_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.mms_path
     *
     * @return the value of user_service_send.mms_path
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getMmsPath() {
        return mmsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.mms_path
     *
     * @param mmsPath the value for user_service_send.mms_path
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setMmsPath(String mmsPath) {
        this.mmsPath = mmsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_service_send.batch_id
     *
     * @return the value of user_service_send.batch_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_service_send.batch_id
     *
     * @param batchId the value for user_service_send.batch_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

	public String getReportTimeStart() {
		return reportTimeStart;
	}

	public void setReportTimeStart(String reportTimeStart) {
		this.reportTimeStart = reportTimeStart;
	}

	public String getReportTimeEnd() {
		return reportTimeEnd;
	}

	public void setReportTimeEnd(String reportTimeEnd) {
		this.reportTimeEnd = reportTimeEnd;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
}