package com.zbensoft.mmsmp.db.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class UserOrderHis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.user_order_his_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String userOrderHisId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.sp_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String spInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.product_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String productInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String chargePhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.order_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.cancel_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.order_route
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer orderRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.order_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.fee
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Double fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.cancel_route
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer cancelRoute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.feature_str
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String featureStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.status
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.version
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.not_disturb_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String notDisturbTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.transaction_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.eff_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private Date effTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.area
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.priority
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.last_batch_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private String lastBatchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order_his.is_package
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    private Integer isPackage;

    private Integer notifySpFlag;
    
    private String orderTimeStart;
    private String orderTimeEnd;
    private String companyName;
    private String companyCode;
    private String provinceCityName;
    private String productName;
    private String productServiceId;
    private Double onDemandFee; 
    private Integer onDemandTimes;      //点播数
    private Double countOnDemandFee;    //点播总费用
    private Integer newOrderNumber;      //新增订购数
    private Double newOrderNumberFee;      //新增订购总费用
    private Double countFee;      //总费用
    private Integer countMMSDownlink;      //彩信下行数
    private Integer countTerminalArrival;      //终端到达数
	private Double orderFee;
    private Integer orderTimes;
    private Double countOrderFee;
    private Integer unsubscribe;       //退订次数
    private Integer currentChargeOrder;       //当前收费订购数
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.user_order_his_id
     *
     * @return the value of user_order_his.user_order_his_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getUserOrderHisId() {
        return userOrderHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.user_order_his_id
     *
     * @param userOrderHisId the value for user_order_his.user_order_his_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setUserOrderHisId(String userOrderHisId) {
        this.userOrderHisId = userOrderHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.phone_number
     *
     * @return the value of user_order_his.phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.phone_number
     *
     * @param phoneNumber the value for user_order_his.phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.sp_info_id
     *
     * @return the value of user_order_his.sp_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getSpInfoId() {
        return spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.sp_info_id
     *
     * @param spInfoId the value for user_order_his.sp_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setSpInfoId(String spInfoId) {
        this.spInfoId = spInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.product_info_id
     *
     * @return the value of user_order_his.product_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getProductInfoId() {
        return productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.product_info_id
     *
     * @param productInfoId the value for user_order_his.product_info_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setProductInfoId(String productInfoId) {
        this.productInfoId = productInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.charge_phone_number
     *
     * @return the value of user_order_his.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getChargePhoneNumber() {
        return chargePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.charge_phone_number
     *
     * @param chargePhoneNumber the value for user_order_his.charge_phone_number
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setChargePhoneNumber(String chargePhoneNumber) {
        this.chargePhoneNumber = chargePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.order_time
     *
     * @return the value of user_order_his.order_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.order_time
     *
     * @param orderTime the value for user_order_his.order_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.cancel_time
     *
     * @return the value of user_order_his.cancel_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.cancel_time
     *
     * @param cancelTime the value for user_order_his.cancel_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.order_route
     *
     * @return the value of user_order_his.order_route
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getOrderRoute() {
        return orderRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.order_route
     *
     * @param orderRoute the value for user_order_his.order_route
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setOrderRoute(Integer orderRoute) {
        this.orderRoute = orderRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.order_type
     *
     * @return the value of user_order_his.order_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.order_type
     *
     * @param orderType the value for user_order_his.order_type
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.fee
     *
     * @return the value of user_order_his.fee
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.fee
     *
     * @param fee the value for user_order_his.fee
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.cancel_route
     *
     * @return the value of user_order_his.cancel_route
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getCancelRoute() {
        return cancelRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.cancel_route
     *
     * @param cancelRoute the value for user_order_his.cancel_route
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setCancelRoute(Integer cancelRoute) {
        this.cancelRoute = cancelRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.feature_str
     *
     * @return the value of user_order_his.feature_str
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getFeatureStr() {
        return featureStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.feature_str
     *
     * @param featureStr the value for user_order_his.feature_str
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setFeatureStr(String featureStr) {
        this.featureStr = featureStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.status
     *
     * @return the value of user_order_his.status
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.status
     *
     * @param status the value for user_order_his.status
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.version
     *
     * @return the value of user_order_his.version
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.version
     *
     * @param version the value for user_order_his.version
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.not_disturb_time
     *
     * @return the value of user_order_his.not_disturb_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getNotDisturbTime() {
        return notDisturbTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.not_disturb_time
     *
     * @param notDisturbTime the value for user_order_his.not_disturb_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setNotDisturbTime(String notDisturbTime) {
        this.notDisturbTime = notDisturbTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.transaction_id
     *
     * @return the value of user_order_his.transaction_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.transaction_id
     *
     * @param transactionId the value for user_order_his.transaction_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.eff_time
     *
     * @return the value of user_order_his.eff_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Date getEffTime() {
        return effTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.eff_time
     *
     * @param effTime the value for user_order_his.eff_time
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setEffTime(Date effTime) {
        this.effTime = effTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.area
     *
     * @return the value of user_order_his.area
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.area
     *
     * @param area the value for user_order_his.area
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.priority
     *
     * @return the value of user_order_his.priority
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.priority
     *
     * @param priority the value for user_order_his.priority
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.last_batch_id
     *
     * @return the value of user_order_his.last_batch_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public String getLastBatchId() {
        return lastBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.last_batch_id
     *
     * @param lastBatchId the value for user_order_his.last_batch_id
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setLastBatchId(String lastBatchId) {
        this.lastBatchId = lastBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order_his.is_package
     *
     * @return the value of user_order_his.is_package
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public Integer getIsPackage() {
        return isPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order_his.is_package
     *
     * @param isPackage the value for user_order_his.is_package
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    public void setIsPackage(Integer isPackage) {
        this.isPackage = isPackage;
    }

	public String getOrderTimeStart() {
		return orderTimeStart;
	}

	public void setOrderTimeStart(String orderTimeStart) {
		this.orderTimeStart = orderTimeStart;
	}

	public String getOrderTimeEnd() {
		return orderTimeEnd;
	}

	public void setOrderTimeEnd(String orderTimeEnd) {
		this.orderTimeEnd = orderTimeEnd;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getProvinceCityName() {
		return provinceCityName;
	}

	public void setProvinceCityName(String provinceCityName) {
		this.provinceCityName = provinceCityName;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getNotifySpFlag() {
		return notifySpFlag;
	}

	public void setNotifySpFlag(Integer notifySpFlag) {
		this.notifySpFlag = notifySpFlag;
	}

	public String getProductServiceId() {
		return productServiceId;
	}

	public void setProductServiceId(String productServiceId) {
		this.productServiceId = productServiceId;
	}

	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public Double getOnDemandFee() {
		return onDemandFee;
	}

	public void setOnDemandFee(Double onDemandFee) {
		this.onDemandFee = onDemandFee;
	}

	public Integer getOnDemandTimes() {
		return onDemandTimes;
	}

	public void setOnDemandTimes(Integer onDemandTimes) {
		this.onDemandTimes = onDemandTimes;
	}

	public Double getCountOnDemandFee() {
		return countOnDemandFee;
	}

	public void setCountOnDemandFee(Double countOnDemandFee) {
		this.countOnDemandFee = countOnDemandFee;
	}

	public Integer getNewOrderNumber() {
		return newOrderNumber;
	}

	public void setNewOrderNumber(Integer newOrderNumber) {
		this.newOrderNumber = newOrderNumber;
	}

	public Double getNewOrderNumberFee() {
		return newOrderNumberFee;
	}

	public void setNewOrderNumberFee(Double newOrderNumberFee) {
		this.newOrderNumberFee = newOrderNumberFee;
	}

	public Double getCountFee() {
		return countFee;
	}

	public void setCountFee(Double countFee) {
		this.countFee = countFee;
	}

	public Integer getCountMMSDownlink() {
		return countMMSDownlink;
	}

	public void setCountMMSDownlink(int i) {
		this.countMMSDownlink = i;
	}

	public Integer getCountTerminalArrival() {
		return countTerminalArrival;
	}

	public void setCountTerminalArrival(Integer countTerminalArrival) {
		this.countTerminalArrival = countTerminalArrival;
	}
public Double getOrderFee() {
		return orderFee;
	}

	public void setOrderFee(Double orderFee) {
		this.orderFee = orderFee;
	}

	public Integer getOrderTimes() {
		return orderTimes;
	}

	public void setOrderTimes(Integer orderTimes) {
		this.orderTimes = orderTimes;
	}

	public Double getCountOrderFee() {
		return countOrderFee;
	}

	public void setCountOrderFee(Double countOrderFee) {
		this.countOrderFee = countOrderFee;
	}

	public Integer getUnsubscribe() {
		return unsubscribe;
	}

	public void setUnsubscribe(Integer unsubscribe) {
		this.unsubscribe = unsubscribe;
	}

	public Integer getCurrentChargeOrder() {
		return currentChargeOrder;
	}

	public void setCurrentChargeOrder(Integer currentChargeOrder) {
		this.currentChargeOrder = currentChargeOrder;
	}

	public void setCountMMSDownlink(Integer countMMSDownlink) {
		this.countMMSDownlink = countMMSDownlink;
	}

}