package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.AlarmManger;

public interface AlarmMangerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alarm_manger
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	int deleteByPrimaryKey(String alarmKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alarm_manger
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	int insert(AlarmManger record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alarm_manger
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	int insertSelective(AlarmManger record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alarm_manger
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	AlarmManger selectByPrimaryKey(String alarmKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alarm_manger
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	int updateByPrimaryKeySelective(AlarmManger record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alarm_manger
	 * @mbg.generated  Mon Jun 12 11:08:25 CST 2017
	 */
	int updateByPrimaryKey(AlarmManger record);

	List<AlarmManger> selectPage(AlarmManger record);

	void deleteAll();

	int count(AlarmManger alarmManger);

	List<AlarmManger> selectAll();
}