package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.ApplicationServer;

public interface ApplicationServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    int deleteByPrimaryKey(String applicationServerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    int insert(ApplicationServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    int insertSelective(ApplicationServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    ApplicationServer selectByPrimaryKey(String applicationServerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    int updateByPrimaryKeySelective(ApplicationServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Wed Aug 30 12:15:28 CST 2017
     */
    int updateByPrimaryKey(ApplicationServer record);
    ApplicationServer selectByName(String name);
    List<ApplicationServer> selectPage(ApplicationServer record);
 	int count(ApplicationServer applicationServer);
	boolean isExist(ApplicationServer applicationServer);
}