package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.BlackWhiteList;


public interface BlackWhiteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_white_list
     *
     * @mbg.generated Wed Aug 29 09:56:44 CST 2018
     */
    int deleteByPrimaryKey(String blackWhiteList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_white_list
     *
     * @mbg.generated Wed Aug 29 09:56:44 CST 2018
     */
    int insert(BlackWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_white_list
     *
     * @mbg.generated Wed Aug 29 09:56:44 CST 2018
     */
    int insertSelective(BlackWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_white_list
     *
     * @mbg.generated Wed Aug 29 09:56:44 CST 2018
     */
    BlackWhiteList selectByPrimaryKey(String blackWhiteList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_white_list
     *
     * @mbg.generated Wed Aug 29 09:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(BlackWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_white_list
     *
     * @mbg.generated Wed Aug 29 09:56:44 CST 2018
     */
    int updateByPrimaryKey(BlackWhiteList record);
    
     List<BlackWhiteList> selectPage(BlackWhiteList record);
    
    int count(BlackWhiteList record);
}