package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.CpInfo;

public interface CpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    int deleteByPrimaryKey(String cpInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    int insert(CpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    int insertSelective(CpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    CpInfo selectByPrimaryKey(String cpInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    int updateByPrimaryKeySelective(CpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbg.generated Fri Aug 24 09:11:03 CST 2018
     */
    int updateByPrimaryKey(CpInfo record);
    
    List<CpInfo> selectPage(CpInfo record);
    
    int count(CpInfo record);
}