package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.ProductService;

public interface ProductServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_service
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    int deleteByPrimaryKey(String productServiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_service
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    int insert(ProductService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_service
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    int insertSelective(ProductService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_service
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    ProductService selectByPrimaryKey(String productServiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_service
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    int updateByPrimaryKeySelective(ProductService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_service
     *
     * @mbg.generated Mon Sep 03 09:13:58 CST 2018
     */
    int updateByPrimaryKey(ProductService record);
    
    List<ProductService> selectPage(ProductService record);
    
    int count(ProductService record);
    
    ProductService getProductServiceByOnDemandAccess(ProductService record);
    
    ProductService getServiceIDbyProductid(ProductService record);
    List<ProductService> getProductInfo(ProductService productInfo);
    List<ProductService> getSpProductId(String cpAccessId);
    
    ProductService getVasServiceRelation(ProductService record);
    
    int queryContentCount(ProductService record);
}