package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SysLog;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Thu Jun 29 11:16:44 CST 2017
     */
    int deleteByPrimaryKey(String sysLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Thu Jun 29 11:16:44 CST 2017
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Thu Jun 29 11:16:44 CST 2017
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Thu Jun 29 11:16:44 CST 2017
     */
    SysLog selectByPrimaryKey(String sysLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Thu Jun 29 11:16:44 CST 2017
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Thu Jun 29 11:16:44 CST 2017
     */
    int updateByPrimaryKey(SysLog record);

	List<SysLog> selectPage(SysLog record);

	void deleteAll();

	int count(SysLog sysLog);
}