package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SysMenu;
import com.zbensoft.mmsmp.db.domain.SysMenuUserMenuParam;

public interface SysMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	SysMenu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKey(SysMenu record);

	int deleteAll();

	List<SysMenu> selectPage(SysMenu record);

	int count(SysMenu menu);
	SysMenu selectByMenuName(String name);

	List<SysMenu> getUserMenus(SysMenuUserMenuParam sysMenuUserMenuParam);

	List<SysMenu> getRoleResources(String id);

	List<SysMenu> findAll();

	void deleteRoleRescours(String roleId);

	void saveRoleRescours(SysMenu resources);

	SysMenu getMenuByMenuKeyWord(String keyWord);

}