package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SysRoleUserKey;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_role_user
     *
     * @mbg.generated Wed Jun 07 15:37:39 CST 2017
     */
    int deleteByPrimaryKey(SysRoleUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_role_user
     *
     * @mbg.generated Wed Jun 07 15:37:39 CST 2017
     */
    int insert(SysRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_role_user
     *
     * @mbg.generated Wed Jun 07 15:37:39 CST 2017
     */
    int insertSelective(SysRoleUserKey record);
    int updateByPrimaryKeySelective(SysRoleUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	int updateByPrimaryKey(SysRoleUserKey record);

	int deleteAll();

	List<SysRoleUserKey> selectPage(SysRoleUserKey record);

	SysRoleUserKey selectByPrimaryKey(SysRoleUserKey key);
	int count(SysRoleUserKey sysRoleUser);
	List<SysRoleUserKey> selectByUserId(String userId);
}