package com.zbensoft.mmsmp.db.mapper;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SysUser;

public interface SysUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	SysUser selectByPrimaryKey(String userId);

	List<SysUser> selectPage(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user
	 *
	 * @mbg.generated Wed May 24 13:36:02 CST 2017
	 */
	int updateByPrimaryKey(SysUser record);

	SysUser findByName(String userName);

	int deleteAll();

	SysUser selectByUserName(String userName);

	int count(SysUser roleUser);
}