package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.ApplicationServer;
import com.zbensoft.mmsmp.db.domain.TaskType;

public interface ApplicationServerService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    int deleteByPrimaryKey(String applicationServerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    int insert(ApplicationServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    int insertSelective(ApplicationServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    ApplicationServer selectByPrimaryKey(String applicationServerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    int updateByPrimaryKeySelective(ApplicationServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_server
     *
     * @mbg.generated Thu Aug 03 10:47:31 VET 2017
     */
    int updateByPrimaryKey(ApplicationServer record);
    ApplicationServer selectByName(String name);
    List<ApplicationServer> selectPage(ApplicationServer record);
 	int count(ApplicationServer applicationServer);
 	boolean isExist(ApplicationServer applicationServer);
}