package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.Proxypaymessage;

public interface ProxypaymessageService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxypaymessage
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    int deleteByPrimaryKey(String globalmessageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxypaymessage
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    int insert(Proxypaymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxypaymessage
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    int insertSelective(Proxypaymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxypaymessage
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    Proxypaymessage selectByPrimaryKey(String globalmessageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxypaymessage
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    int updateByPrimaryKeySelective(Proxypaymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxypaymessage
     *
     * @mbg.generated Fri Sep 07 10:32:52 CST 2018
     */
    int updateByPrimaryKey(Proxypaymessage record);
    
    List<Proxypaymessage> selectPage(Proxypaymessage record);
    
    int count(Proxypaymessage record);
    
    Proxypaymessage getCooperKeyMessage(String globalmessageid);
    
    Proxypaymessage getProxyPayMessage(Proxypaymessage record);
    
    Proxypaymessage getProxyPayMessageById(String globalmessageid);
}
