package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SpAccess;

public interface SpAccessService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_access
     *
     * @mbg.generated Fri Aug 24 14:06:15 CST 2018
     */
    int deleteByPrimaryKey(String spInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_access
     *
     * @mbg.generated Fri Aug 24 14:06:15 CST 2018
     */
    int insert(SpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_access
     *
     * @mbg.generated Fri Aug 24 14:06:15 CST 2018
     */
    int insertSelective(SpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_access
     *
     * @mbg.generated Fri Aug 24 14:06:15 CST 2018
     */
    SpAccess selectByPrimaryKey(String spInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_access
     *
     * @mbg.generated Fri Aug 24 14:06:15 CST 2018
     */
    int updateByPrimaryKeySelective(SpAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_access
     *
     * @mbg.generated Fri Aug 24 14:06:15 CST 2018
     */
    int updateByPrimaryKey(SpAccess record);
    List<SpAccess> selectPage(SpAccess record);

	int count(SpAccess record);

    String getMaxServiceAccessNumber(String spid);
}