package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SpInfo;

public interface SpInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_info
     *
     * @mbg.generated Fri Aug 24 09:35:46 CST 2018
     */
    int deleteByPrimaryKey(String spInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_info
     *
     * @mbg.generated Fri Aug 24 09:35:46 CST 2018
     */
    int insert(SpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_info
     *
     * @mbg.generated Fri Aug 24 09:35:46 CST 2018
     */
    int insertSelective(SpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_info
     *
     * @mbg.generated Fri Aug 24 09:35:46 CST 2018
     */
    SpInfo selectByPrimaryKey(String spInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_info
     *
     * @mbg.generated Fri Aug 24 09:35:46 CST 2018
     */
    int updateByPrimaryKeySelective(SpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_info
     *
     * @mbg.generated Fri Aug 24 09:35:46 CST 2018
     */
    int updateByPrimaryKey(SpInfo record);
    
    List<SpInfo> selectPage(SpInfo record);

	int count(SpInfo record);
}