package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.SpUrl;

public interface SpUrlService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_url
     *
     * @mbg.generated Mon Aug 27 10:18:53 CST 2018
     */
    int deleteByPrimaryKey(String spUrlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_url
     *
     * @mbg.generated Mon Aug 27 10:18:53 CST 2018
     */
    int insert(SpUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_url
     *
     * @mbg.generated Mon Aug 27 10:18:53 CST 2018
     */
    int insertSelective(SpUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_url
     *
     * @mbg.generated Mon Aug 27 10:18:53 CST 2018
     */
    SpUrl selectByPrimaryKey(String spUrlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_url
     *
     * @mbg.generated Mon Aug 27 10:18:53 CST 2018
     */
    int updateByPrimaryKeySelective(SpUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_url
     *
     * @mbg.generated Mon Aug 27 10:18:53 CST 2018
     */
    int updateByPrimaryKey(SpUrl record);
    
    List<SpUrl> selectPage(SpUrl record);

   	int count(SpUrl record);
}