package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import org.springframework.stereotype.Service;

import com.zbensoft.mmsmp.db.domain.SysRole;
public interface SysRoleService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	SysRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKey(SysRole record);

	List<SysRole> selectPage(SysRole record);

	boolean isRoleExist(SysRole role);

	void deleteAll();
	SysRole selectByRoleName(String name);
	int count(SysRole role);
}