package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.TestTerminalProductKey;

public interface TestTerminalProductService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_terminal_product
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    int deleteByPrimaryKey(TestTerminalProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_terminal_product
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    int insert(TestTerminalProductKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_terminal_product
     *
     * @mbg.generated Sat Sep 15 10:04:48 CST 2018
     */
    int insertSelective(TestTerminalProductKey record);
    
    TestTerminalProductKey selectByTestTerminalId(String TestTerminalId);
    
    List<TestTerminalProductKey> selectByProductInfoId(String productInfoId);
}
