package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.UserRecv;

public interface UserRecvService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recv
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int deleteByPrimaryKey(String userRecvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recv
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int insert(UserRecv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recv
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int insertSelective(UserRecv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recv
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    UserRecv selectByPrimaryKey(String userRecvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recv
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int updateByPrimaryKeySelective(UserRecv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recv
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int updateByPrimaryKey(UserRecv record);
    
    List<UserRecv> selectPage(UserRecv record);
    
    int count(UserRecv record);

	UserRecv getLatestMoOrderMsgText(UserRecv userRecv);
}
