package com.zbensoft.mmsmp.api.service.api;

import java.util.List;

import com.zbensoft.mmsmp.db.domain.UserOrderHis;

public interface UserOrderHisService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_his
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int deleteByPrimaryKey(String userOrderHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_his
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int insert(UserOrderHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_his
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int insertSelective(UserOrderHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_his
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    UserOrderHis selectByPrimaryKey(String userOrderHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_his
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int updateByPrimaryKeySelective(UserOrderHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order_his
     *
     * @mbg.generated Mon Aug 27 11:26:29 CST 2018
     */
    int updateByPrimaryKey(UserOrderHis record);
    
    List<UserOrderHis> selectPage(UserOrderHis record);
    
    int count(UserOrderHis record);
}
